---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE,
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
options(scipen = 999)
```

# {careroll}

<!-- badges: start -->
<!-- badges: end -->


## Installation

You can install the development version of careroll from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("andrewallenbruce/careroll", build_vignettes = TRUE)
```

``` r
# install.packages("remotes")
remotes::install_github("andrewallenbruce/careroll", build_vignettes = TRUE)
```

```{r echo=TRUE}
library(careroll)
```

# Yearly

## National

### Total

```{r}
total_yr <- levels(period = "year", level = "national", group = "total")

total_yr |> 
  dplyr::filter(year == 2017 | year == 2021) |> 
  change_year(bene_tot)

total_yr |> 
  dplyr::mutate(rolling_mean = slider::slide_mean(bene_tot, before = 1)) |> 
  change_year(bene_tot)
```

### Orig & MA

```{r}
origMA_yr <- levels(period = "year", level = "national", group = "origMA")

origMA_yr |> 
  dplyr::mutate(pct_orig = bene_orig / (bene_orig + bene_ma_oth),
                pct_ma = bene_ma_oth / (bene_orig + bene_ma_oth)) |> 
  change_year(bene_orig) |> 
  dplyr::rename(orig_change = change_abs, orig_pct_change = change_pct) |> 
  change_year(bene_ma_oth) |> 
  dplyr::rename(ma_change = change_abs, ma_pct_change = change_pct)
```

### Aged

```{r}
aged_yr <- levels(period = "year", level = "national", group = "aged")

aged_yr |> 
  dplyr::mutate(pct_aged = bene_aged_tot / bene_tot,
                pct_esrd = bene_aged_esrd / bene_aged_tot,
                pct_no_esrd = bene_aged_no_esrd / bene_aged_tot) |> 
  change_year(bene_aged_tot) |> 
  dplyr::rename(aged_change = change_abs, aged_pct_change = change_pct)
```

### Disabled

```{r}
dsb_yr <- levels(period = "year", level = "national", group = "disabled")

dsb_yr |> 
  dplyr::mutate(pct_dsb = bene_dsb_tot / bene_tot,
                pct_dsb_esrd = bene_dsb_esrd_and_only_esrd / bene_dsb_tot,
                pct_dsb_no_esrd = bene_dsb_no_esrd / bene_dsb_tot) |> 
  change_year(bene_dsb_tot) |> 
  dplyr::rename(dsb_change = change_abs, dsb_pct_change = change_pct)
```

### Part A & B

```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
partAB_yr <- levels(period = "year", level = "national", group = "partAB")

partAB_yr |> 
  dplyr::mutate(pct_ab = bene_ab_total / bene_tot,
                pct_ab_orig = bene_ab_orig / bene_ab_total,
                pct_ab_ma_oth = bene_ab_ma_oth / bene_ab_total) |> 
  change_year(bene_ab_total) |> 
  dplyr::rename(ab_change = change_abs, ab_pct_change = change_pct)
```


### Part D

```{r}
# Prescription Drug (Part D) Beneficiaries
partD_yr <- levels(period = "year", level = "national", group = "partD")

partD_yr |> 
  dplyr::mutate(pct_rx = bene_rx_tot / bene_tot,
                pct_rx_pdp = bene_rx_pdp / bene_rx_tot,
                pct_rx_mapd = bene_rx_mapd / bene_rx_tot) |> 
  change_year(bene_rx_tot) |> 
  dplyr::rename(rx_change = change_abs, rx_pct_change = change_pct)
```


<br>

## State

```{r}
# Medicare Beneficiaries
total_state_yr <- levels(period = "year", level = "state", group = "total")
```

```{r}
# Aged Beneficiaries
aged_state_yr <- levels(period = "year", level = "state", group = "aged")
```

```{r}
# Disabled Beneficiaries
dsb_state_yr <- levels(period = "year", level = "state", group = "disabled")
```

```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
partAB_state_yr <- levels(period = "year", level = "state", group = "partAB")
```

```{r}
# Prescription Drug (Part D) Beneficiaries
partD_state_yr <- levels(period = "year", level = "state", group = "partD")
```


<br>

## County

```{r}
# Medicare Beneficiaries
total_county_yr <- levels(period = "year", level = "county", group = "total")
```

```{r}
# Aged Beneficiaries
aged_county_yr <- levels(period = "year", level = "county", group = "aged")
```

```{r}
# Disabled Beneficiaries
dsb_county_yr <- levels(period = "year", level = "county", group = "disabled")
```

```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
partAB_county_yr <- levels(period = "year", level = "county", group = "partAB")
```

```{r}
# Prescription Drug (Part D) Beneficiaries
partD_county_yr <- levels(period = "year", level = "county", group = "partD")
```


# Month

## National

```{r}
# Medicare Beneficiaries
levels(period = "month", level = "national", group = "total")
```


```{r}
# Aged Beneficiaries
levels(period = "month", level = "national", group = "aged")
```


```{r}
# Disabled Beneficiaries
levels(period = "month", level = "national", group = "disabled")
```


```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
levels(period = "month", level = "national", group = "partAB")
```


```{r}
# Prescription Drug (Part D) Beneficiaries
levels(period = "month", level = "national", group = "partD")
```

## State

```{r}
# Medicare Beneficiaries
levels(period = "month", level = "state", group = "total")
```


```{r}
# Aged Beneficiaries
levels(period = "month", level = "state", group = "aged")
```


```{r}
# Disabled Beneficiaries
levels(period = "month", level = "state", group = "disabled")
```


```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
levels(period = "month", level = "state", group = "partAB")
```


```{r}
# Prescription Drug (Part D) Beneficiaries
levels(period = "month", level = "state", group = "partD")
```

## County


```{r}
# Medicare Beneficiaries
levels(period = "month", level = "county", group = "total")
```


```{r}
# Aged Beneficiaries
levels(period = "month", level = "county", group = "aged")
```


```{r}
# Disabled Beneficiaries
levels(period = "month", level = "county", group = "disabled")
```


```{r}
# Beneficiaries with Hospital (Part A) and Supplementary (Part B)
levels(period = "month", level = "county", group = "partAB")
```


```{r}
# Prescription Drug (Part D) Beneficiaries
levels(period = "month", level = "county", group = "partD")
```
