# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "bene_geo_lvl", # <careroll>
  "bene_state_abrvtn", # <careroll>
  "bene_state_desc", # <careroll>
  "bene_county_desc", # <careroll>
  "bene_fips_cd", # <careroll>
  "tot_benes", # <careroll>
  "orgnl_mdcr_benes", # <careroll>
  "ma_and_oth_benes", # <careroll>
  "aged_tot_benes", # <careroll>
  "aged_esrd_benes", # <careroll>
  "aged_no_esrd_benes", # <careroll>
  "dsbld_tot_benes", # <careroll>
  "dsbld_esrd_and_esrd_only_benes", # <careroll>
  "dsbld_no_esrd_benes", # <careroll>
  "a_b_tot_benes", # <careroll>
  "a_b_orgnl_mdcr_benes", # <careroll>
  "a_b_ma_and_oth_benes", # <careroll>
  "prscrptn_drug_tot_benes", # <careroll>
  "prscrptn_drug_pdp_benes", # <careroll>
  "prscrptn_drug_mapd_benes", # <careroll>
  "fips", # <careroll>
  "state", # <careroll>
  "county", # <careroll>
  "month", # <levels>
  "year", # <levels>
  "bene_tot", # <levels>
  "bene_orig", # <levels>
  "bene_ma_oth", # <levels>
  "state", # <levels>
  "state_name", # <levels>
  "county", # <levels>
  NULL
))
